version: "3.7"

services:

  mysql:
    image: mysql:8.0
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${APP_SEED_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${APP_SEED_MYSQL_DATABASE}
      MYSQL_USER: ${APP_SEED_MYSQL_USER}
      MYSQL_PASSWORD: ${APP_SEED_MYSQL_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/mysql:/var/lib/mysql
    networks:
      mysql-net:
        ipv4_address: 10.21.21.5

networks:
  mysql-net:
    name: thundercode-mysql-net
    driver: bridge
    ipam:
      config:
        - subnet: 10.21.21.0/24
